database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  # the password
  password: 12345678
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:mysql://localhost:3306/DWGettingStarted

server:
  applicationConnectors:
    - type: http
      port: 9003
  adminConnectors:
    - type: http
      port: 9004